# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Split_expense',
            name='group',
            field=models.CharField(default='12423rwdfgsd1324r', max_length=255),
            preserve_default=False,
        ),
    ]
